#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Public ~/Work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

[[ -n $selected ]] || exit 0

selected_name=$(basename "$selected" | tr . _)

if [[ -z $(tmux list-clients 2>/dev/null) ]]; then
    tmux new-session -A -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -d -s $selected_name -c $selected
fi

tmux switch-client -t $selected_name
