live_config_reload = true

[window]
dynamic_padding = true

[shell]
program = "/usr/bin/zsh"

[font]
size = 14
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[colors.primary]
background = '#101010'

[colors.normal]
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#FFAA88'
blue = '#7788AA'
magenta = '#D7007D'
cyan = '#708090'
white = '#DDDDDD'

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
